baseURL = "http://example.org/"
languageCode = "en-us"
disableKinds = ["taxonomy"]

[build]
    writeStats = true

[params]
    title = "Ejang Stephanie Ambikoh"
    author = "Ejang Stephanie Ambikoh"
    description = "The site it,s about my Cv"
    copyright = "copy right 2024"
    theme = "dark" # `dark` or `light`

    # Profile section
    [params.profile]
        name = "Ejang Stephanie"
        title = "Abbr., E.S"
        photo = "images/steph.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-linkedin-in"
        url = ""
        title = "LinkedIn"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/stephanie448"
        title = "GitHub"
		
		[[params.social.list]]
        icon = "ai ai-google-scholar"
        url = "#"
        title = "Google Scholar"
		
		[[params.social.list]]
        icon = "ai ai-researchgate"
        url = "#"
        title = "ResearchGate"		

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Advaced level"
        college = "GBHS Bangem"
        dates = "2022-2023"
        thesis_title = "Title of the dissertation"
        thesis_link = "#"

        [[params.education.list]]
        degree = "Ordinary Level"
        college = "GBHS Bangem"
        dates = "2021-2022"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"
				
        [[params.language.list]]
        language = "French"
        level = "Basic"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Travelling"
		
		[[params.hobbies.list]]
        interest = "Music"

        [[params.hobbies.list]]
        interest = "Reading"

        [[params.hobbies.list]]
        interest = "Baking"

    [params.aboutme]
        description = "I am a girl, I love my studies and i love what i do. I pray God directs me in the right direction."

    # Projects section
    [params.projects]
        title = "Project"

        [[params.projects.list]]
        title = "Personal Resume"
        url = "#"
        description = "This project contains a brief introduction of my about'Education,social media platforms."
		
		[[params.projects.list]]
        title = "Host on github pages using hogu"
        url = "https://github.com/stephanie448"
        description = "This concisesd of all the various steps and technologies used like ;html,node.js etc used in creating this project,the challenges faced,solution used in solving them and finally the outcome"

    # Skills section
    [params.skills]
        title = "Skills"

        [[params.skills.list]]
        skill = "html"
        skillrating = 60 # out of 100
                
        [[params.skills.list]]
        skill = "C++"
        skillrating = 60
		
        [[params.skills.list]]
        skill = "C programming"
        skillrating = 60
